// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KitAttachedLab.Data.Models;

public partial class DeliveryDetail
{
    public int Id { get; set; }

    public string Description { get; set; }

    public int? DeliveryId { get; set; }

    public int? KitId { get; set; }

    public int? Quantity { get; set; }

    public virtual Delivery Delivery { get; set; }

    public virtual Kit Kit { get; set; }
}