// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KitAttachedLab.Data.Models;

public partial class Delivery
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public int? WarehouseId { get; set; }

    public string Status { get; set; }

    public DateTime? Date { get; set; }

    public virtual ICollection<DeliveryDetail> DeliveryDetails { get; set; } = new List<DeliveryDetail>();

    public virtual Order Order { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}