// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KitAttachedLab.Data.Models;

public partial class Inventory
{
    public int Id { get; set; }

    public int? WarehouseId { get; set; }

    public int? KitId { get; set; }

    public int? Quantity { get; set; }

    public virtual Kit Kit { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}