// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KitAttachedLab.Data.Models;

public partial class Kit
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? Quantity { get; set; }

    public string Image { get; set; }

    public decimal? Price { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? CategoryId { get; set; }

    public int? LabId { get; set; }

    public bool? IsActive { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<DeliveryDetail> DeliveryDetails { get; set; } = new List<DeliveryDetail>();

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual Lab Lab { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Support> Supports { get; set; } = new List<Support>();
}