// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KitAttachedLab.Data.Models;

public partial class Order
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string CreatedAt { get; set; }

    public string Status { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Note { get; set; }

    public string PaymentMethod { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<Delivery> Deliveries { get; set; } = new List<Delivery>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();

    public virtual User User { get; set; }
}