// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KitAttachedLab.Data.Models;

public partial class SupportDetail
{
    public int Id { get; set; }

    public string Description { get; set; }

    public int? SupportId { get; set; }

    public virtual Support Support { get; set; }
}