// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KitAttachedLab.Data.Models;

public partial class Support
{
    public int Id { get; set; }

    public int? KitId { get; set; }

    public int? NumberSupport { get; set; }

    public string RuleSupport { get; set; }

    public int? UserId { get; set; }

    public virtual Kit Kit { get; set; }

    public virtual ICollection<SupportDetail> SupportDetails { get; set; } = new List<SupportDetail>();

    public virtual User User { get; set; }
}