// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KitAttachedLab.Data.Models;

public partial class Warehouse
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public virtual ICollection<Delivery> Deliveries { get; set; } = new List<Delivery>();

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();
}